"""Landscape feature functions, one module per paper class (Table 1).

Re-exports every implemented feature under `mola.features`, so callers don't need to know which
class module a given feature lives in — `from mola.features import dist_x_avg, sup_avg_neig` reads
the same regardless of how many classes are behind it.
"""

from mola.features.evolvability import (
    diff_f_avg_neig,
    diff_f_dist_x_avg_neig,
    dist_f_avg_neig,
    dist_f_dist_x_avg_neig,
    dist_x_avg_neig,
    hv_avg_neig,
    hvd_avg_neig,
    inc_avg_neig,
    inf_avg_neig,
    nhv_avg_neig,
    sup_avg_neig,
)
from mola.features.global_ import (
    dist_f_avg,
    dist_f_max,
    dist_x_avg,
    dist_x_max,
    dist_x_nd_avg,
    dist_x_nd_max,
    f_cor,
    fdc,
    hv,
    nd_n,
    rank_avg,
    rank_ent,
    rank_max,
    supp_n,
)
from mola.features.multimodality import (
    eval_aws,
    length_aws,
    nd_per_plo,
    plo_dist_avg,
    plo_dist_max,
    plo_n,
    slo_dist_avg,
    slo_dist_max,
    slo_n,
)
from mola.features.ruggedness import (
    diff_f_cor_neig,
    diff_f_dist_x_cor_neig,
    dist_f_cor_neig,
    dist_f_dist_x_cor_neig,
    dist_x_cor_neig,
    hv_cor_neig,
    hvd_cor_neig,
    inc_cor_neig,
    inf_cor_neig,
    nhv_cor_neig,
    sup_cor_neig,
)

__all__ = [
    "diff_f_avg_neig",
    "diff_f_cor_neig",
    "diff_f_dist_x_avg_neig",
    "diff_f_dist_x_cor_neig",
    "dist_f_avg",
    "dist_f_avg_neig",
    "dist_f_cor_neig",
    "dist_f_dist_x_avg_neig",
    "dist_f_dist_x_cor_neig",
    "dist_f_max",
    "dist_x_avg",
    "dist_x_avg_neig",
    "dist_x_cor_neig",
    "dist_x_max",
    "dist_x_nd_avg",
    "dist_x_nd_max",
    "eval_aws",
    "f_cor",
    "fdc",
    "hv",
    "hv_avg_neig",
    "hv_cor_neig",
    "hvd_avg_neig",
    "hvd_cor_neig",
    "inc_avg_neig",
    "inc_cor_neig",
    "inf_avg_neig",
    "inf_cor_neig",
    "length_aws",
    "nd_n",
    "nd_per_plo",
    "nhv_avg_neig",
    "nhv_cor_neig",
    "plo_dist_avg",
    "plo_dist_max",
    "plo_n",
    "rank_avg",
    "rank_ent",
    "rank_max",
    "slo_dist_avg",
    "slo_dist_max",
    "slo_n",
    "sup_avg_neig",
    "sup_cor_neig",
    "supp_n",
]
